// <auto-generated />
using System;
using AntiFraudService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AntiFraudService.Infrastructure.Migrations
{
    [DbContext(typeof(AntiFraudDbContext))]
    [Migration("20250408203239_InitialCreateAccumulatedTransactions")]
    partial class InitialCreateAccumulatedTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntiFraudService.Domain.Models.DailyAccumulatedTransaction", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("AccumulatedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("AccountId", "Date");

                    b.HasIndex("AccountId");

                    b.ToTable("DailyAccumulatedTransactions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
